all:  compile run

compile:
	javac -d target /home/void_id/Desktop/Java_Modules/Java_Module_05/ex01/Chat-folder/src/main/java/fr/school42/chat/**/*.java

run:
	java -cp target fr.school42.chat.app.Program

clean:
	rm -rf target
